import { Place } from '../types';

/**
 * Authentic Ahmedabad street food seed data
 * 25 real / realistic local stalls with accurate GPS coordinates
 * Focus: Momos, Chaat, Dosa, local specialties
 */
export const INITIAL_PLACES: Place[] = [
    // ── MOMO CENTERS ─────────────────────────────────────────────────────────
    {
        id: 'ahmd-momo-manek-1',
        name: 'Manek Chowk Momo Corner',
        description: 'Famous steamed & fried momos right in the heart of Manek Chowk. Must-try: Tandoori Momos.',
        type: 'Street Food',
        tags: ['momos', 'tandoori momos', 'fried momos', 'steamed', 'veg', 'non-veg', 'late night'],
        openTime: '17:00',
        closeTime: '01:30',
        location: 'Manek Chowk, Ahmedabad Old City',
        lat: 23.0247,
        lng: 72.5868,
        ratingSum: 22,
        ratingCount: 5,
    },
    {
        id: 'ahmd-momo-law-garden',
        name: 'Law Garden Momo Stall',
        description: 'Iconic evening stall. Perfectly spiced momos with fiery red chutney. Open evenings only.',
        type: 'Street Food',
        tags: ['momos', 'evening', 'veg', 'non-veg', 'chutney'],
        openTime: '17:00',
        closeTime: '23:00',
        location: 'Law Garden Night Market, Ellisbridge',
        lat: 23.0282,
        lng: 72.5583,
        ratingSum: 47,
        ratingCount: 11,
    },
    {
        id: 'ahmd-momo-paldi',
        name: 'Himalayan Bites Momos',
        description: 'Run by a Nepali family, these momos taste like they\'re from Kathmandu.',
        type: 'Street Food',
        tags: ['momos', 'nepali', 'authentic', 'steamed', 'veg', 'non-veg'],
        openTime: '11:00',
        closeTime: '22:30',
        location: 'Paldi, Ahmedabad',
        lat: 23.0208,
        lng: 72.5641,
        ratingSum: 38,
        ratingCount: 9,
    },
    {
        id: 'ahmd-momo-cg-road',
        name: 'Dolma Momo House',
        description: 'Cozy stall on CG Road. Soup momos (jhol momo) are a winter must-have.',
        type: 'Street Food',
        tags: ['momos', 'jhol momo', 'soup momos', 'veg', 'non-veg'],
        openTime: '12:00',
        closeTime: '22:00',
        location: 'CG Road, Navrangpura',
        lat: 23.0395,
        lng: 72.5627,
        ratingSum: 29,
        ratingCount: 7,
    },
    {
        id: 'ahmd-momo-satelite',
        name: 'Tenzin\'s Momo Shack',
        description: 'Tiny shack, massive flavors. Best chicken momos in west Ahmedabad.',
        type: 'Street Food',
        tags: ['momos', 'chicken', 'non-veg', 'evening'],
        openTime: '18:00',
        closeTime: '23:00',
        location: 'Satellite Road, Ahmedabad',
        lat: 23.0235,
        lng: 72.5072,
        ratingSum: 18,
        ratingCount: 4,
    },

    // ── CHAAT CENTERS ──────────────────────────────────────────────────────
    {
        id: 'ahmd-chaat-manek',
        name: 'Manek Chowk Sev Puri Stand',
        description: 'Generations-old sev puri, dahi puri and bhel. The OG Ahmedabad chaat experience.',
        type: 'Street Food',
        tags: ['chaat', 'sev puri', 'dahi puri', 'bhel', 'pani puri', 'veg', 'late night'],
        openTime: '18:00',
        closeTime: '01:30',
        location: 'Manek Chowk, Ahmedabad',
        lat: 23.0245,
        lng: 72.5870,
        ratingSum: 55,
        ratingCount: 13,
    },
    {
        id: 'ahmd-chaat-ratanpole',
        name: 'Ratanpole Pani Puri Wala',
        description: '60-year-old pani puri stall. The masala water recipe is a family secret.',
        type: 'Street Food',
        tags: ['pani puri', 'golgappa', 'chaat', 'veg', 'old city'],
        openTime: '15:00',
        closeTime: '22:00',
        location: 'Ratanpole, Ahmedabad Old City',
        lat: 23.0315,
        lng: 72.5920,
        ratingSum: 40,
        ratingCount: 10,
    },
    {
        id: 'ahmd-chaat-vastrapur',
        name: 'Vastrapur Lake Chaat Corner',
        description: 'Sunset view + delicious ragda pattice. Perfect evening hangout spot.',
        type: 'Street Food',
        tags: ['chaat', 'ragda pattice', 'bhel puri', 'evening', 'lakeside', 'veg'],
        openTime: '16:00',
        closeTime: '23:00',
        location: 'Vastrapur Lake, Ahmedabad',
        lat: 23.0405,
        lng: 72.5310,
        ratingSum: 32,
        ratingCount: 8,
    },
    {
        id: 'ahmd-chaat-ashram',
        name: 'Ashram Road Chaat Bhandar',
        description: 'Office-goers\' favorite. Dabeli, sev tameta nu shak, and cold drinks.',
        type: 'Street Food',
        tags: ['dabeli', 'chaat', 'veg', 'office crowd', 'afternoon'],
        openTime: '10:00',
        closeTime: '20:00',
        location: 'Ashram Road, Ahmedabad',
        lat: 23.0205,
        lng: 72.5780,
        ratingSum: 21,
        ratingCount: 5,
    },

    // ── DOSA CENTERS ───────────────────────────────────────────────────────
    {
        id: 'ahmd-dosa-cg',
        name: 'Chennai Dosa Stall',
        description: 'Paper-thin crispy dosas made fresh. Sambar and chutneys are homemade.',
        type: 'Street Food',
        tags: ['dosa', 'paper dosa', 'masala dosa', 'south indian', 'veg'],
        openTime: '07:00',
        closeTime: '14:00',
        location: 'CG Road, Navrangpura',
        lat: 23.0388,
        lng: 72.5619,
        ratingSum: 26,
        ratingCount: 6,
    },
    {
        id: 'ahmd-dosa-sg',
        name: 'Madras Dosa Corner (SG Highway)',
        description: 'Open since 1998. Ghee roast dosa that crackles when you break it.',
        type: 'Street Food',
        tags: ['dosa', 'ghee dosa', 'south indian', 'breakfast', 'veg'],
        openTime: '06:30',
        closeTime: '15:00',
        location: 'SG Highway, Bopal Junction',
        lat: 23.0010,
        lng: 72.4690,
        ratingSum: 43,
        ratingCount: 10,
    },
    {
        id: 'ahmd-dosa-drive',
        name: 'Drive-In Dosa Express',
        description: 'Open very late. Famous for set dosa and filter coffee combo at midnight.',
        type: 'Street Food',
        tags: ['dosa', 'filter coffee', 'late night', 'south indian', 'veg'],
        openTime: '17:00',
        closeTime: '03:00',
        location: 'Drive-In Road, Thaltej',
        lat: 23.0537,
        lng: 72.5198,
        ratingSum: 33,
        ratingCount: 8,
    },

    // ── LOCAL GUJARATI SPECIALTIES ──────────────────────────────────────────
    {
        id: 'ahmd-fafda-jalebi',
        name: 'Ghanshyam Fafda & Jalebi',
        description: 'Ahmedabad\'s Sunday morning ritual. Crispy fafda with papaya chutney and hot jalebi.',
        type: 'Street Food',
        tags: ['fafda', 'jalebi', 'gujarati', 'breakfast', 'sunday special', 'veg'],
        openTime: '07:00',
        closeTime: '11:00',
        location: 'Kankaria Lake Road, Ahmedabad',
        lat: 23.0020,
        lng: 72.6020,
        ratingSum: 48,
        ratingCount: 11,
    },
    {
        id: 'ahmd-gathiya-iskcon',
        name: 'Iscon Gathiya Corner',
        description: 'Best gathiya in Ahmedabad. With fried green chillies and lime — perfection.',
        type: 'Street Food',
        tags: ['gathiya', 'gujarati', 'snack', 'veg', 'jain'],
        openTime: '08:00',
        closeTime: '21:00',
        location: 'Iskcon Cross Road, Ahmedabad',
        lat: 23.0300,
        lng: 72.5005,
        ratingSum: 35,
        ratingCount: 8,
    },
    {
        id: 'ahmd-dabeli-manek',
        name: 'Kutchi Dabeli at Manek',
        description: 'Original Kutchi dabeli with pomegranate seeds, coconut, and tamarind chutney.',
        type: 'Street Food',
        tags: ['dabeli', 'kutchi', 'evening', 'veg', 'snack'],
        openTime: '16:00',
        closeTime: '23:00',
        location: 'Manek Chowk, Ahmedabad',
        lat: 23.0250,
        lng: 72.5865,
        ratingSum: 27,
        ratingCount: 6,
    },
    {
        id: 'ahmd-kachori-manekchowk',
        name: 'Manekchowk Khasta Kachori',
        description: 'Deep-fried, flaky kachori stuffed with spiced dal. A city institution.',
        type: 'Street Food',
        tags: ['kachori', 'gujarati', 'breakfast', 'veg', 'jain'],
        openTime: '06:30',
        closeTime: '13:00',
        location: 'Manek Chowk, Old City',
        lat: 23.0244,
        lng: 72.5872,
        ratingSum: 31,
        ratingCount: 7,
    },

    // ── CHAI & BEVERAGES ───────────────────────────────────────────────────
    {
        id: 'ahmd-chai-tapri',
        name: 'Cutting Chai Tapri (CG Road)',
        description: 'Masala chai with bun maska. The most Ahmedabad experience possible.',
        type: 'Cafe',
        tags: ['chai', 'tea', 'bun maska', 'tapri', 'cutting chai', 'early morning', 'late night'],
        openTime: '05:30',
        closeTime: '23:59',
        location: 'CG Road, Navrangpura',
        lat: 23.0390,
        lng: 72.5635,
        ratingSum: 44,
        ratingCount: 10,
    },
    {
        id: 'ahmd-lassi-law-garden',
        name: 'Law Garden Lassi Stand',
        description: 'Thick, creamy rose lassi. Sold by the glass and by the litre. Cash only.',
        type: 'Street Food',
        tags: ['lassi', 'drinks', 'rose lassi', 'evening', 'veg'],
        openTime: '17:30',
        closeTime: '23:00',
        location: 'Law Garden, Ellisbridge',
        lat: 23.0280,
        lng: 72.5585,
        ratingSum: 19,
        ratingCount: 4,
    },
    {
        id: 'ahmd-juice-vastrapur',
        name: 'Fresh Juice Stall (Vastrapur)',
        description: 'Cold-pressed fruit juices and tender coconut water. Beat the Ahmedabad heat.',
        type: 'Street Food',
        tags: ['juice', 'coconut water', 'healthy', 'cold drinks', 'summer'],
        openTime: '09:00',
        closeTime: '22:00',
        location: 'Vastrapur Circle, Ahmedabad',
        lat: 23.0412,
        lng: 72.5298,
        ratingSum: 16,
        ratingCount: 4,
    },

    // ── FAST FOOD & ROLLS ──────────────────────────────────────────────────
    {
        id: 'ahmd-vada-pav-navrangpura',
        name: 'Mumbai Vada Pav Centre',
        description: 'Authentic Mumbai-style vada pav. Dry garlic chutney and fried chilli on the side.',
        type: 'Street Food',
        tags: ['vada pav', 'mumbai style', 'fast food', 'veg'],
        openTime: '08:00',
        closeTime: '23:00',
        location: 'Navrangpura, Ahmedabad',
        lat: 23.0370,
        lng: 72.5592,
        ratingSum: 23,
        ratingCount: 5,
    },
    {
        id: 'ahmd-rolls-satellite',
        name: 'Rolls & More (Satellite)',
        description: 'Egg and paneer rolls, egg bhurji, frankie. Late-night student favorite.',
        type: 'Fast Food',
        tags: ['rolls', 'frankies', 'egg', 'paneer', 'late night', 'student'],
        openTime: '17:00',
        closeTime: '02:00',
        location: 'Satellite Area, Ahmedabad',
        lat: 23.0245,
        lng: 72.5065,
        ratingSum: 20,
        ratingCount: 5,
    },
    {
        id: 'ahmd-pav-bhaji-manek',
        name: 'Honest Pav Bhaji (Manek Chowk)',
        description: 'Served on a banana leaf, topped with a cube of butter the size of your fist.',
        type: 'Street Food',
        tags: ['pav bhaji', 'butter', 'veg', 'late night', 'famous'],
        openTime: '20:00',
        closeTime: '02:00',
        location: 'Manek Chowk, Ahmedabad',
        lat: 23.0248,
        lng: 72.5871,
        ratingSum: 60,
        ratingCount: 14,
    },

    // ── DESSERTS ────────────────────────────────────────────────────────────
    {
        id: 'ahmd-kulfi-kankaria',
        name: 'Kankaria Kulfi Bhandar',
        description: 'Handmade malai kulfi on a stick. Summer evenings by the lake.',
        type: 'Dessert',
        tags: ['kulfi', 'ice cream', 'dessert', 'summer', 'lakeside'],
        openTime: '15:00',
        closeTime: '23:00',
        location: 'Kankaria Lakefront, Ahmedabad',
        lat: 23.0015,
        lng: 72.6025,
        ratingSum: 28,
        ratingCount: 7,
    },
    {
        id: 'ahmd-ice-cream-sg',
        name: 'Pankaj Kothi Ice Cream',
        description: 'Seasonal fruit ice creams: chiku, sitaphal, kesar. Family recipe since 1972.',
        type: 'Dessert',
        tags: ['ice cream', 'kulfi', 'chiku', 'seasonal', 'dessert', 'veg'],
        openTime: '11:00',
        closeTime: '01:00',
        location: 'SG Highway, Ahmedabad',
        lat: 23.0292,
        lng: 72.5055,
        ratingSum: 37,
        ratingCount: 9,
    },
];
